### ISSUE TITLE
grive-indicator

### ISSUE THREAD

**Issue by joksik** [LyzardKing/grive-indicator#2]
hi i use arch and i install grive-indicator from aur https://aur.archlinux.org/packages/grive-indicator-git/
when i want start grive-indicator i have this errors

Traceback (most recent call last):
  File "/usr/bin/grive-indicator", line 11, in <module>
    load_entry_point('grive-indicator==1.0', 'console_scripts', 'grive-indicator')()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 570, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2755, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2409, in load
    return self.resolve()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2415, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.6/site-packages/grive_indicator/__init__.py", line 15, in <module>
    from grive_indicator.UI import settings, configure, InfoDialog
  File "/usr/lib/python3.6/site-packages/grive_indicator/UI/settings.py", line 14, in <module>
    from ..tools import getIcon, Config, ind, root_dir, autostart_file, griveignore_init
  File "/usr/lib/python3.6/site-packages/grive_indicator/tools.py", line 7, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by LyzardKing** [comment]
Hi
You have to install python3-requests (or the arch equivalent)
I'm not the maintainer of the aur package, so you should ping them and let them know.
Then it can be added to the package requirements
